-- 1. 사용자 정보를 저장할 테이블 (unique_id를 식별자로 사용)
create table if not exists users (
  unique_id text primary key,
  name text not null,
  is_admin boolean default false,
  created_at timestamptz default now()
);

-- 2. 진단 결과를 저장할 테이블
create table if not exists assessments (
  id bigint generated by default as identity primary key,
  user_id text references users(unique_id) on delete cascade,
  type text not null check (type in ('PRE', 'POST')),
  scores jsonb not null,
  created_at timestamptz default now()
);

-- 3. Row Level Security (RLS) 활성화
alter table users enable row level security;
alter table assessments enable row level security;

-- 4. 보안 정책 설정 (RLS Policies)
-- 기존 정책이 있다면 삭제 (재실행 시 에러 방지)
drop policy if exists "Enable access for all users" on users;
drop policy if exists "Enable access for all assessments" on assessments;

-- 간편 로그인(이름+고유번호) 방식을 위해 익명 사용자(Public)에게 모든 권한(SELECT, INSERT, UPDATE, DELETE) 허용
create policy "Enable access for all users" 
on users 
for all 
using (true) 
with check (true);

create policy "Enable access for all assessments" 
on assessments 
for all 
using (true) 
with check (true);

-- 5. 초기 관리자 계정 생성 (이미 존재하면 무시)
-- unique_id: 'admin1234', name: '관리자' 인 계정을 관리자로 등록합니다.
insert into users (unique_id, name, is_admin)
values ('admin1234', '관리자', true)
on conflict (unique_id) do update set is_admin = true;